### ISSUE TITLE
Button Icons

### ISSUE THREAD

**Issue by brianbodollo** [dev-onenetworkecommerce/aia#100]
What is the difference of 
![image](https://cloud.githubusercontent.com/assets/8682886/10597599/d7d633c0-7722-11e5-8419-c6fe651ee10d.png)
to
![image](https://cloud.githubusercontent.com/assets/8682886/10597607/ea50c48e-7722-11e5-9db2-70a55f265230.png)

**Comment by srph** [comment]
What do you mean? I don't get it.

**Comment by srph** [comment]
I just checked the page, this is probably redundant or just out place. Need to fix this soon.

**Comment by brianbodollo** [comment]
ill just remove the 'with icons inside' part

**Comment by srph** [comment]
Better yet, please move it. It would be nice to have a preview of each size variant with icons.

**Comment by brianbodollo** [comment]
https://github.com/dev-onenetworkecommerce/aia/pull/103
