### ISSUE TITLE
Improve Dropdown styling

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#106]
AFAICR, it looks pretty far away from the design.

**Comment by JefMari** [comment]
I mention the current design to @fleenerlemon and he is ok for it. so this should be closed  :+1:

**Comment by srph** [comment]
I think our dropdowns are smaller than the design?

**Comment by JefMari** [comment]
i mean the current dropdown's mark up is accepted. Even though its a bit smaller than the given design, is it OK and accepted by sir @fleenerlemon.
or
We really need enlarge dropdowns?

**Comment by srph** [comment]
Can you try and give me your opinion whether we should push it forward or not

**Comment by srph** [comment]
NVM, just talked to Lemon
