### ISSUE TITLE
Loader Style

### ISSUE THREAD

**Issue by brianbodollo** [dev-onenetworkecommerce/aia#109]
![image](https://cloud.githubusercontent.com/assets/8682886/10780530/5e412508-7d79-11e5-8b3a-0c0a2049a6bd.png)

**VS**

![image](https://cloud.githubusercontent.com/assets/8682886/10780534/726b784e-7d79-11e5-86be-c000540018b5.png)

**Comment by srph** [comment]
Examples would be nice, because that would give others a concrete idea.

**Comment by JefMari** [comment]
Check this out http://codepen.io/TaniaLD/pen/oKxep

**Comment by srph** [comment]
We need this later tonight. Unless they provide any, we're pushing the loader design in the works (PR).

**Comment by maebe22** [comment]
![image](https://cloud.githubusercontent.com/assets/8682886/10780530/5e412508-7d79-11e5-8b3a-0c0a2049a6bd.png)

**VS**

![image](https://cloud.githubusercontent.com/assets/8682886/10780534/726b784e-7d79-11e5-86be-c000540018b5.png)

**Comment by srph** [comment]
Decision: The 3 circles.
