### ISSUE TITLE
button -disable style also available in button disabled attribute

### ISSUE THREAD

**Issue by JefMari** [dev-onenetworkecommerce/aia#142]
In a button that is disabled not in class but in attribute like this
![image](https://cloud.githubusercontent.com/assets/12628112/10959609/841d291a-83b5-11e5-965e-949548faee57.png)

**Comment by srph** [comment]
I don't get it

**Comment by JefMari** [comment]
In [Primer disable-state](http://primercss.io/buttons/#disabled-state) , style in button with `-disable` should have the same with button that is `disabled` in atrribute :)

**Comment by srph** [comment]
We already have this.

**Comment by JefMari** [comment]
ohh. my fault. coz i only see the example :)

**Comment by srph** [comment]
I don't really promote it tho.
