### ISSUE TITLE
Utility for bold headings

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#184]
As per, https://github.com/dev-onenetworkecommerce/aia/issues/171, I missed out to address "all custom headings are bold". Well, not really, but I think we should add a utility for bold headings.

**Comment by srph** [comment]
How about `_heading-bold`?

cc @juztinlazaro @vistajess @JefMari @maebe22

**Comment by JefMari** [comment]
Good! :100:
