### ISSUE TITLE
Status Circles

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#20]
![screen shot 2015-09-12 at 11 01 16 pm](https://cloud.githubusercontent.com/assets/5093058/9832080/5b15b5c4-59a2-11e5-8225-518d510fc6b5.png)

Not sure what to call 'em. Maybe it's a badge too?

**Comment by srph** [comment]
- Badge Circle
- Badge Status

?

cc @vistajess @JefMari @juztinlazaro @maebe22

**Comment by johnjullies** [comment]
Saw this on phackers slack so I'm going to suggest one, how about `active-indicators`? or `active-signal` or `active-mode`.

**Comment by srph** [comment]
Thanks @johnjullies. :+1: 

However, our designer _just_ suggested this morning to name it as `badge-status` as there are more color variations.
