### ISSUE TITLE
Document colors of links in alert

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#201]
![screen shot 2015-11-24 at 8 43 35 pm](https://cloud.githubusercontent.com/assets/5093058/11367063/2987a2fa-92ec-11e5-962b-fa19d7e3463e.png)

Using a darker shade of the variant was the only way to fix this (see https://github.com/dev-onenetworkecommerce/aia/pull/200).

I think we need to take of this in the docs / store the colors in variables.

**Comment by srph** [comment]
We might also need to notify the designers, @JefMari

**Comment by JefMari** [comment]
Copy that!
