### ISSUE TITLE
active buttons

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#31]
We need styling for `:focus` state.

**Comment by maebe22** [comment]
there is, but the same with the style of ```:hover```

**Comment by maebe22** [comment]
i think it should be another class e? kapag yung ```:focus```

**Comment by srph** [comment]
I don't think this is necessary. Nor anybody in the company thinks that making buttons as radio input would be an awesome idea at this stage. Not that we have any use-cases for it anyway.
