### ISSUE TITLE
same width on every page number

### ISSUE THREAD

**Issue by brianbodollo** [dev-onenetworkecommerce/aia#58]
should it will be better if every page-number buttons has the same width?

**Comment by srph** [comment]
Min-width, I think

**Comment by brianbodollo** [comment]
+1

**Comment by brianbodollo** [comment]
idk but this works fine for me na @srph

**Comment by srph** [comment]
Was min-width already added to the pagination? I don't remember. Mind referencing a PR / the file if it is?

**Comment by brianbodollo** [comment]
nope but it seems there is no problem with padding, btw ill change it nalang

**Comment by srph** [comment]
There's no problem. But as you suggested, it looks subtly weird for 1, 2, 3. What if we have 9, 10, 11?

Keep the `padding`, and just add a `min-width`.

**Comment by srph** [comment]
https://github.com/dev-onenetworkecommerce/aia/pull/65
