### ISSUE TITLE
Badge on List Group

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#61]
- [x] Make `.badge` work with `.list-group`
- [x] Docs

This one liner should do it

``` sass
> .badge {
  float: right;
}
```

**Comment by brianbodollo** [comment]
do you mean like this? 

![badge](https://cloud.githubusercontent.com/assets/8682886/10356965/3595910e-6daf-11e5-8a1e-24d319c8ea0b.png)

**Comment by srph** [comment]
Ah, no, to the right I meant haha. The left is reserved for icons. You can check [Primer CSS](http://primercss.io/nav/#menu)

Reference the PR here when you're done

**Comment by brianbodollo** [comment]
```
> .menuitem > .badge {
    float: right;
}
```

results to this >
![badge](https://cloud.githubusercontent.com/assets/8682886/10357017/141c0548-6db0-11e5-9cba-5c3d54082b10.png)

**Comment by srph** [comment]
Yea, exactly. Can we continue this with your PR?

**Comment by brianbodollo** [comment]
ill sending a PR now

**Comment by srph** [comment]
https://github.com/dev-onenetworkecommerce/aia/pull/63
