### ISSUE TITLE
Form Errors

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#68]
Basic idea: http://primercss.io/forms/#form-group-validation

**Comment by brianbodollo** [comment]
why not making the border red like this one 
![form-error](https://cloud.githubusercontent.com/assets/8682886/10421188/e1afab7c-70d5-11e5-85a3-224bdb7534fb.png)

(image source: semantic-ui.com)

**Comment by srph** [comment]
Good idea. Although, we need a design directly from the designers.

**Comment by srph** [comment]
https://github.com/dev-onenetworkecommerce/aia/pull/119
