### ISSUE TITLE
Non-responsive docs nav

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#75]
![capture](https://cloud.githubusercontent.com/assets/5093058/10507747/51e66512-7355-11e5-8b1a-ffd3a6204506.png)

Good catch by @johnjullies #phackers

**Comment by johnjullies** [comment]
Thanks for the mention. Awesome guidelines and components. I had TILs :smile:

**Comment by srph** [comment]
Looks good to me now. I forgot when this was fixed (or was it ever fixed?).

![screen shot 2015-11-17 at 5 10 09 pm](https://cloud.githubusercontent.com/assets/5093058/11207061/f2a88a4a-8d4d-11e5-9e80-04073c522ec9.png)
