### ISSUE TITLE
error when doing npm run docs:watch:script

### ISSUE THREAD

**Issue by brianbodollo** [dev-onenetworkecommerce/aia#79]
![screenshot from 2015-10-16 10 41 02](https://cloud.githubusercontent.com/assets/8682886/10532556/479ef0b8-73f2-11e5-88bf-1fc8c7f33774.png)

**Comment by srph** [comment]
Can you do a fresh install of the node modules?

``` bash
rm -rf node_modules && npm install
```

**Comment by brianbodollo** [comment]
![image](https://cloud.githubusercontent.com/assets/8682886/10534165/e3d759de-7406-11e5-80ae-496d97e9f871.png)

**Comment by srph** [comment]
Did you pull from the `master` branch, and did a fresh install?

The latest commit (https://github.com/dev-onenetworkecommerce/aia/commit/5caf168d0a4bbbae0bf64f3af28e0d8657d8dd78) fixes your issue with `npm run doc:server` (but not for `npm run docs:watch:script`). Pull from the `master` branch.

**Comment by brianbodollo** [comment]
ye fresh installed.

**Comment by maebe22** [comment]
new error when running npm docs:server 

![image](https://cloud.githubusercontent.com/assets/8682886/10535050/a38cfb12-7411-11e5-9970-e54ebacee276.png)

**Comment by brianbodollo** [comment]
is this resolved? please let me know

**Comment by srph** [comment]
This isn't happening to @JefMari. Can you just do a fresh install, instead? ..

**Comment by brianbodollo** [comment]
everythings fine right now,
