### ISSUE TITLE
Button: Small and Default's sizes are nearly identical

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#92]
![screen shot 2015-10-16 at 4 31 11 pm](https://cloud.githubusercontent.com/assets/5093058/10537291/5ac41534-7423-11e5-8863-97bc8323056e.png)

We'll need to fix our sizes soon.

**Comment by maebe22** [comment]
that's because they have the same height

**Comment by srph** [comment]
wat..
wat..

aren't we supposed to say, "we need to adjust our sizes."

**Comment by JefMari** [comment]
Current: 
![1](https://cloud.githubusercontent.com/assets/12628112/10784095/1758e3ce-7d97-11e5-828a-99f1b7dd3307.PNG)

My Propose Size:
![2](https://cloud.githubusercontent.com/assets/12628112/10784111/2891b634-7d97-11e5-87e3-df6b1e1bc7dc.PNG)

**Comment by srph** [comment]
Noted. I'll think about it

**Comment by srph** [comment]
Will be addressed by https://github.com/dev-onenetworkecommerce/aia/issues/169
