### ISSUE TITLE
Panel Body + Body weird border color

### ISSUE THREAD

**Issue by srph** [dev-onenetworkecommerce/aia#94]
![screen shot 2015-10-16 at 4 32 48 pm](https://cloud.githubusercontent.com/assets/5093058/10537321/91515198-7423-11e5-9977-bb8a00108c85.png)

The issue here is panel does not have any border color, as seen here.

![screen shot 2015-10-16 at 4 33 27 pm](https://cloud.githubusercontent.com/assets/5093058/10537333/a4f6df7e-7423-11e5-8fe0-bbefba05efb9.png)

**Comment by brianbodollo** [comment]
should the solution for this is just add border-color? or am i getting it wrong?

**Comment by srph** [comment]
Yea, as in `1px solid $brand-gray-lt` I guess

**Comment by maebe22** [comment]
https://github.com/dev-onenetworkecommerce/aia/pull/99

**Comment by brianbodollo** [comment]
i dont think the Shipping panel here has a class of `body`. i suppose its `heading`

**Comment by brianbodollo** [comment]
just in case it really needs fixes, i opened a pull request 
https://github.com/dev-onenetworkecommerce/aia/pull/99

**Comment by srph** [comment]
Huh?
